export const PAGE_SIZE = 5;
export const TABLE_HEADER_BG_COLOR = '#E0E0E0';
export const NATIONALITIES: { [x: string]: string } = {
  AU: 'Australia',
  BR: 'Brazil',
  CA: 'Canada',
  CH: 'Switzerland',
  DE: 'Germany',
  DK: 'Denmark',
  ES: 'Spain',
  FI: 'Finland',
  FR: 'France',
  GB: 'United Kingdom',
  IE: 'Ireland',
  IN: 'India',
  IR: 'Iran',
  MX: 'Mexico',
  NL: 'Netherlands',
  NO: 'Norway',
  NZ: 'New Zealand',
  RS: 'Serbia',
  TR: 'Turkey',
  UA: 'Ukraine',
  US: 'United States',
};
